var numbers = [1, 2, 3];
numbers.push(4);
console.log(numbers);
var names = ["Matheus", "João"];
names.push("Fernanda");
var nums = [100, 2];
nums.push(3);
console.log(nums);
var arr1 = [1, "Teste", true, [], { nome: "Lucas" }];
console.log(arr1);
